### ISSUE TITLE
Custom Geocoder causes search box to disappear

### ISSUE THREAD

**Issue by mikeri1000** [Esri/Viewer#39]
When I try to use a custom geocode service, and configure the commonConfig.js according to the wiki instructions (custom geocode url, queryForOrg set to false), the search box disappears from the site and other elements such as layers, legend, no longer show up when selected.

**Comment by jgravois** [comment]
this is happening because your custom geocoder is stripped from the array [here](https://github.com/Esri/Viewer/blob/master/js/CreateGeocoder.js#L297).

i was able to get the template configured properly after manually supplying a `singleLineFieldName` (in addition to `url` for the geocode helperService in the commonConfig.js

```
geocode: [{
  url: location.protocol + "//tasks.arcgisonline.com/ArcGIS/rest/services/Locators/TA_Address_NA_10/GeocodeServer",
  //needs to match the actual input parameter for your own service        
  singleLineFieldName: "SingleLine"
}]
```

**Comment by mikeri1000** [comment]
Thanks, that got it working once i figured out what the singleLineFieldName should be for my service. The wiki instructions i was referring to are these: https://github.com/Esri/basic-viewer-template/wiki/Configure-utility-services

**Comment by jgravois** [comment]
glad i could help.  i've submitted a PR here to add a few code comments to clarify the requirement and edited the wiki to reflect the same.  thanks for reporting.

**Comment by kazakovks** [comment]
With the addition of its geocoder disappeared AutoFill. Wherein said property autokompete can not find?
