### ISSUE TITLE
Ability to select feature and zoom to it from URL

### ISSUE THREAD

**Issue by driskull** [Esri/Viewer#43]
from devsummit user request

**Comment by Nataliya1** [comment]
It works in ArcGIS online hosted version of the Viewer. But it doesn't seem to work in the downloadable version. I downloaded the app and put it on our web server. But the app doesn't search the features from preconfigured layer, it just geocodes based on default geocoder? I would appreciate any suggestions how to bypass the geocoder, and query the layer instead.

Thank you, Nataliya

**Comment by kellyhutchins** [comment]
@Nataliya1  you have to configure the locally hosted version to use the search layers. The easiest way to do this is to specify the appid of your configured app in the config/defaults.js file.

**Comment by Nataliya1** [comment]
@kellyhutchins I tried to add the appid from the configured app to local app on my server, and it worked, but it overrides my configurations. The reasons I downloaded the app is because the ArcGIS online hosted app has some limitations, like - I cannot remove 'Title' bar or change the selection symbology. 
Please see the image below on how I have the layer setup for URL search:

![viewer_url](https://cloud.githubusercontent.com/assets/6840324/10394219/5ae7af26-6e5b-11e5-9623-c6c6387a6f23.PNG)

Thank you.

**Comment by kellyhutchins** [comment]
I suspect that 14 isn't a valid layer id. In order to find the layer id you'll need to look at the web map json.  You can view the web map json by inspecting your browsers network traffic to find the request to ArcGIS Online for your web map id. Here's an example of what the web map json looks like. If your web map is public you can replace the existing id (2c653...) with your web map id and run the url below. 

http://www.arcgis.com/sharing/rest/content/items/2c6532a53f00447fb1aede3b1e2d1ff4/data?f=json
