### ISSUE TITLE
Date attribute subtracts a day???

### ISSUE THREAD

**Issue by mlrgisonline** [Esri/Viewer#45]
When I import an ESRI shapefile with a DATE attribute the table and popup's in ArcGIS Online oddly subtract one day from all my dates. My organizational map is built in this viewer so I haven't tried an another to see if it's a symptom of the viewer or ArcGIS Online in general. NOTICE: I can subsequently export the data from ArcGIS Online to my desktop and when I open the attribute table in my Desktop ArcGIS the date is fine. I'm guessing it's something to do with ArcGIS Online and how it reads dates? I can forward you a copy of my dataset if you want to see for yourself.

**Comment by mlrgisonline** [comment]
So for example the date attribute for a particular polygon is "12/21/2007". When I import that shapefile into ArcGIS Online the date in the table and pop-up reads "December 20, 2007".

**Comment by jgravois** [comment]
my guess is that this is caused by the fact that somewhere along the line we are interpreting a 12:00am GMT timestamp and later your browser converts to your local timezone (a few hours prior)

this isn't the best place to post feedback on the general behavior of ArcGIS Online, as its intended specifically for reporting bugs in the Viewer template.  as an alternative, please either log a technical support ticket or post somewhere like [Geonet](https://geonet.esri.com/community/discussions-lobby) or gis.stackexchange instead.
